FROM node:20-alpine

WORKDIR /usr/src/app/todo-frontend

COPY --chown=node:node ./package*.json .

RUN npm ci

COPY --chown=node:node . .

EXPOSE 5173

USER node

CMD ["npm", "run", "dev", "--", "--host"]
