services:
  dev-mongodb:
    image: mongo
    container_name: todo-dev-mongodb
    ports:
      - 3456:27017
    networks:
      - dev-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=the_username
      - MONGO_INITDB_ROOT_PASSWORD=the_password
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  dev-redis:
    depends_on:
      - dev-mongodb
    image: redis
    container_name: todo-dev-redis
    ports:
      - 6379:6379
    networks:
      - dev-network

  dev-server:
    depends_on:
      - dev-mongodb
      - dev-redis
    build:
      context: ./todo-backend
      dockerfile: Dockerfile.dev
    container_name: todo-dev-server
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://the_username:the_password@todo-dev-mongodb:27017/the_database
      REDIS_URL: redis://todo-dev-redis:6379
    volumes:
      - ./todo-backend:/usr/src/app/todo-backend
      - /usr/src/app/node_modules
    networks:
      - dev-network

  dev-client:
    depends_on:
      - dev-server
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.dev
    container_name: todo-dev-client
    ports:
      - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://dev-server:3000
    volumes:
      - ./todo-frontend:/usr/src/app/todo-frontend
      - /usr/src/app/node_modules
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
