FROM node:20-alpine

WORKDIR /usr/src/app/todo-backend

# Install curl for the healthcheck
RUN apk add --no-cache curl

# Install dependencies
COPY --chown=node:node ./package*.json ./
RUN npm ci

COPY --chown=node:node . .

EXPOSE 3000

USER node

CMD ["npm", "run", "dev"]
