name: Component tests

on:
  push:
    branches: [ main ]

jobs:
  component-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-app/todo-frontend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run component tests
        run: npm run test:run -- ./src/Todos/__tests__
