name: E2E Tests

on:
  push:
    branches: [ main ]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-app
    steps:
      - uses: actions/checkout@v6
      - name: Run E2E stack
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from e2e-test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
